
root: true

extends:
  - "@raycast"
  - "eslint:recommended"
  - "plugin:react-hooks/recommended"

globals:
  React: true
  JSX: true

env:
  browser: true

settings:
  import/resolver:
    typescript:
      project: tsconfig.json

ignorePatterns:
  # Ignore dotfiles
  - ".*.js"
  - "node_modules/"
  - "dist/"
  - "raycast-env.d.ts"

rules:
  react-hooks/exhaustive-deps: warn

  no-unused-vars: off
  '@typescript-eslint/no-unused-vars': warn

  no-redeclare: off
  '@typescript-eslint/no-redeclare': error

  '@typescript-eslint/no-explicit-any': warn

overrides:
  - files: ["*.js?(x)", "*.ts?(x)"]
